version: "3.5"
services:
  mysql:
    image: mariadb:latest
    container_name: pdp_base
    env_file:
      - ./env/mysql.cfg
    volumes:
      - /home/blueuser/pdp/mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  server:
    image: pdp
    container_name: pdp_node
    env_file:
      - ./env/server.cfg
    depends_on:
      - mysql
    ports:
      - "15015:15015"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: pdp_phpmyadmin
    ports:
      - 15016:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=pdp_base
    depends_on:
      - mysql
