FROM node

RUN npm install -g nodemon

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

COPY . .

COPY --chown=node:node . .

USER root

EXPOSE 15015

CMD ["npm", "start"]